export { default as Home } from './Home/HomePage'
export { default as Search } from './Search'
export { default as Detail } from './Detail'
export { default as Error } from './Error'
export { default as Register } from './Register'
